# Generated by Django 3.0.3 on 2020-09-17 14:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0003_auto_20200914_1505'),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('venue', models.CharField(help_text='The venue for appointment', max_length=100)),
                ('start_time', models.CharField(help_text='Appointment time', max_length=100)),
                ('end_time', models.CharField(help_text='End time for appointment', max_length=100)),
                ('Aim', models.TextField()),
                ('user_doc', models.ForeignKey(help_text='Choose the doctor', on_delete=django.db.models.deletion.CASCADE, to='hospital.Doctor')),
            ],
        ),
    ]
