# Generated by Django 3.0.3 on 2020-09-17 14:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0004_appointment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='user_doc',
        ),
        migrations.AddField(
            model_name='appointment',
            name='user_doctor',
            field=models.ForeignKey(blank=True, help_text='Choose the doctor', null=True, on_delete=django.db.models.deletion.CASCADE, to='hospital.Doctor'),
        ),
        migrations.AddField(
            model_name='appointment',
            name='user_specialist',
            field=models.ForeignKey(blank=True, help_text='Choose the Specialist', null=True, on_delete=django.db.models.deletion.CASCADE, to='hospital.Specialist'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='end_time',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='start_time',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='venue',
            field=models.CharField(choices=[('A', 'Hospital'), ('B', 'Home'), ('C', 'Onlinee')], default='H', help_text='The venue for appointment', max_length=2),
        ),
    ]
