# Generated by Django 3.0.3 on 2020-09-23 05:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0009_appointment_user_name'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Payments',
            new_name='Payment',
        ),
    ]
