# Generated by Django 3.0.3 on 2020-09-23 07:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0010_auto_20200923_0504'),
    ]

    operations = [
        migrations.CreateModel(
            name='SpecialistType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('specialist_category', models.CharField(help_text='Enter the type of specialist', max_length=20)),
                ('specialist_type', models.CharField(choices=[('F', 'Freelance'), ('H', 'Hospital')], help_text='The type of specialist', max_length=2)),
            ],
        ),
        migrations.RemoveField(
            model_name='specialist',
            name='hospital',
        ),
        migrations.AddField(
            model_name='appointment',
            name='alert',
            field=models.CharField(blank=True, choices=[('L', 'Low'), ('M', 'Medium'), ('H', 'High')], help_text='Choose the type of alert', max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='specialist',
            name='specialist_type',
            field=models.ForeignKey(blank=True, help_text='choose the type of specialist', null=True, on_delete=django.db.models.deletion.CASCADE, to='hospital.SpecialistType'),
        ),
    ]
